jobInfoFile << (eos_rp::eos_gamma_default == 1.4_rt ? "    " : "[*] ")
            << "eos.eos_gamma_default = " << eos_rp::eos_gamma_default
            << std::endl;
jobInfoFile << (eos_rp::species_1_name == "elec" ? "    " : "[*] ")
            << "eos.species_1_name = " << eos_rp::species_1_name << std::endl;
jobInfoFile << (eos_rp::species_1_gamma == 5. / 3._rt ? "    " : "[*] ")
            << "eos.species_1_gamma = " << eos_rp::species_1_gamma << std::endl;
jobInfoFile << (eos_rp::species_1_mass == 9.10938188e-28_rt ? "    " : "[*] ")
            << "eos.species_1_mass = " << eos_rp::species_1_mass << std::endl;
jobInfoFile << (eos_rp::species_2_name == "hp" ? "    " : "[*] ")
            << "eos.species_2_name = " << eos_rp::species_2_name << std::endl;
jobInfoFile << (eos_rp::species_2_gamma == 5. / 3._rt ? "    " : "[*] ")
            << "eos.species_2_gamma = " << eos_rp::species_2_gamma << std::endl;
jobInfoFile << (eos_rp::species_2_mass == 1.67262158e-24_rt ? "    " : "[*] ")
            << "eos.species_2_mass = " << eos_rp::species_2_mass << std::endl;
jobInfoFile << (eos_rp::species_3_name == "h" ? "    " : "[*] ")
            << "eos.species_3_name = " << eos_rp::species_3_name << std::endl;
jobInfoFile << (eos_rp::species_3_gamma == 5. / 3._rt ? "    " : "[*] ")
            << "eos.species_3_gamma = " << eos_rp::species_3_gamma << std::endl;
jobInfoFile << (eos_rp::species_3_mass == 1.67353251819e-24_rt ? "    "
                                                               : "[*] ")
            << "eos.species_3_mass = " << eos_rp::species_3_mass << std::endl;
jobInfoFile << (eos_rp::species_4_name == "hm" ? "    " : "[*] ")
            << "eos.species_4_name = " << eos_rp::species_4_name << std::endl;
jobInfoFile << (eos_rp::species_4_gamma == 5. / 3._rt ? "    " : "[*] ")
            << "eos.species_4_gamma = " << eos_rp::species_4_gamma << std::endl;
jobInfoFile << (eos_rp::species_4_mass == 1.67444345638e-24_rt ? "    "
                                                               : "[*] ")
            << "eos.species_4_mass = " << eos_rp::species_4_mass << std::endl;
jobInfoFile << (eos_rp::species_5_name == "dp" ? "    " : "[*] ")
            << "eos.species_5_name = " << eos_rp::species_5_name << std::endl;
jobInfoFile << (eos_rp::species_5_gamma == 5. / 3._rt ? "    " : "[*] ")
            << "eos.species_5_gamma = " << eos_rp::species_5_gamma << std::endl;
jobInfoFile << (eos_rp::species_5_mass == 3.34512158e-24_rt ? "    " : "[*] ")
            << "eos.species_5_mass = " << eos_rp::species_5_mass << std::endl;
jobInfoFile << (eos_rp::species_6_name == "d" ? "    " : "[*] ")
            << "eos.species_6_name = " << eos_rp::species_6_name << std::endl;
jobInfoFile << (eos_rp::species_6_gamma == 5. / 3._rt ? "    " : "[*] ")
            << "eos.species_6_gamma = " << eos_rp::species_6_gamma << std::endl;
jobInfoFile << (eos_rp::species_6_mass == 3.34603251819e-24_rt ? "    "
                                                               : "[*] ")
            << "eos.species_6_mass = " << eos_rp::species_6_mass << std::endl;
jobInfoFile << (eos_rp::species_7_name == "h2p" ? "    " : "[*] ")
            << "eos.species_7_name = " << eos_rp::species_7_name << std::endl;
jobInfoFile << (eos_rp::species_7_gamma == 1.4_rt ? "    " : "[*] ")
            << "eos.species_7_gamma = " << eos_rp::species_7_gamma << std::endl;
jobInfoFile << (eos_rp::species_7_mass == 3.34615409819e-24_rt ? "    "
                                                               : "[*] ")
            << "eos.species_7_mass = " << eos_rp::species_7_mass << std::endl;
jobInfoFile << (eos_rp::species_8_name == "dm" ? "    " : "[*] ")
            << "eos.species_8_name = " << eos_rp::species_8_name << std::endl;
jobInfoFile << (eos_rp::species_8_gamma == 5. / 3._rt ? "    " : "[*] ")
            << "eos.species_8_gamma = " << eos_rp::species_8_gamma << std::endl;
jobInfoFile << (eos_rp::species_8_mass == 3.34694345638e-24_rt ? "    "
                                                               : "[*] ")
            << "eos.species_8_mass = " << eos_rp::species_8_mass << std::endl;
jobInfoFile << (eos_rp::species_9_name == "h2" ? "    " : "[*] ")
            << "eos.species_9_name = " << eos_rp::species_9_name << std::endl;
jobInfoFile << (eos_rp::species_9_gamma == 1.4_rt ? "    " : "[*] ")
            << "eos.species_9_gamma = " << eos_rp::species_9_gamma << std::endl;
jobInfoFile << (eos_rp::species_9_mass == 3.34706503638e-24_rt ? "    "
                                                               : "[*] ")
            << "eos.species_9_mass = " << eos_rp::species_9_mass << std::endl;
jobInfoFile << (eos_rp::species_10_name == "hdp" ? "    " : "[*] ")
            << "eos.species_10_name = " << eos_rp::species_10_name << std::endl;
jobInfoFile << (eos_rp::species_10_gamma == 1.4_rt ? "    " : "[*] ")
            << "eos.species_10_gamma = " << eos_rp::species_10_gamma
            << std::endl;
jobInfoFile << (eos_rp::species_10_mass == 5.01865409819e-24_rt ? "    "
                                                                : "[*] ")
            << "eos.species_10_mass = " << eos_rp::species_10_mass << std::endl;
jobInfoFile << (eos_rp::species_11_name == "hd" ? "    " : "[*] ")
            << "eos.species_11_name = " << eos_rp::species_11_name << std::endl;
jobInfoFile << (eos_rp::species_11_gamma == 1.4_rt ? "    " : "[*] ")
            << "eos.species_11_gamma = " << eos_rp::species_11_gamma
            << std::endl;
jobInfoFile << (eos_rp::species_11_mass == 5.01956503638e-24_rt ? "    "
                                                                : "[*] ")
            << "eos.species_11_mass = " << eos_rp::species_11_mass << std::endl;
jobInfoFile << (eos_rp::species_12_name == "hepp" ? "    " : "[*] ")
            << "eos.species_12_name = " << eos_rp::species_12_name << std::endl;
jobInfoFile << (eos_rp::species_12_gamma == 5. / 3._rt ? "    " : "[*] ")
            << "eos.species_12_gamma = " << eos_rp::species_12_gamma
            << std::endl;
jobInfoFile << (eos_rp::species_12_mass == 6.69024316e-24_rt ? "    " : "[*] ")
            << "eos.species_12_mass = " << eos_rp::species_12_mass << std::endl;
jobInfoFile << (eos_rp::species_13_name == "hep" ? "    " : "[*] ")
            << "eos.species_13_name = " << eos_rp::species_13_name << std::endl;
jobInfoFile << (eos_rp::species_13_gamma == 5. / 3._rt ? "    " : "[*] ")
            << "eos.species_13_gamma = " << eos_rp::species_13_gamma
            << std::endl;
jobInfoFile << (eos_rp::species_13_mass == 6.69115409819e-24_rt ? "    "
                                                                : "[*] ")
            << "eos.species_13_mass = " << eos_rp::species_13_mass << std::endl;
jobInfoFile << (eos_rp::species_14_name == "he" ? "    " : "[*] ")
            << "eos.species_14_name = " << eos_rp::species_14_name << std::endl;
jobInfoFile << (eos_rp::species_14_gamma == 5. / 3._rt ? "    " : "[*] ")
            << "eos.species_14_gamma = " << eos_rp::species_14_gamma
            << std::endl;
jobInfoFile << (eos_rp::species_14_mass == 6.69206503638e-24_rt ? "    "
                                                                : "[*] ")
            << "eos.species_14_mass = " << eos_rp::species_14_mass << std::endl;
jobInfoFile << (network_rp::small_x == 1.e-100_rt ? "    " : "[*] ")
            << "network.small_x = " << network_rp::small_x << std::endl;
jobInfoFile << (network_rp::redshift == 30e0_rt ? "    " : "[*] ")
            << "network.redshift = " << network_rp::redshift << std::endl;
jobInfoFile << (network_rp::use_tables == false ? "    " : "[*] ")
            << "network.use_tables = " << network_rp::use_tables << std::endl;
jobInfoFile << (network_rp::use_c12ag_deboer17 == false ? "    " : "[*] ")
            << "network.use_c12ag_deboer17 = " << network_rp::use_c12ag_deboer17
            << std::endl;
jobInfoFile << (integrator_rp::X_reject_buffer == 1.0_rt ? "    " : "[*] ")
            << "integrator.X_reject_buffer = " << integrator_rp::X_reject_buffer
            << std::endl;
jobInfoFile << (integrator_rp::call_eos_in_rhs == true ? "    " : "[*] ")
            << "integrator.call_eos_in_rhs = " << integrator_rp::call_eos_in_rhs
            << std::endl;
jobInfoFile << (integrator_rp::integrate_energy == true ? "    " : "[*] ")
            << "integrator.integrate_energy = "
            << integrator_rp::integrate_energy << std::endl;
jobInfoFile << (integrator_rp::jacobian == 1 ? "    " : "[*] ")
            << "integrator.jacobian = " << integrator_rp::jacobian << std::endl;
jobInfoFile << (integrator_rp::burner_verbose == false ? "    " : "[*] ")
            << "integrator.burner_verbose = " << integrator_rp::burner_verbose
            << std::endl;
jobInfoFile << (integrator_rp::rtol_spec == 1.e-12_rt ? "    " : "[*] ")
            << "integrator.rtol_spec = " << integrator_rp::rtol_spec
            << std::endl;
jobInfoFile << (integrator_rp::rtol_enuc == 1.e-6_rt ? "    " : "[*] ")
            << "integrator.rtol_enuc = " << integrator_rp::rtol_enuc
            << std::endl;
jobInfoFile << (integrator_rp::atol_spec == 1.e-8_rt ? "    " : "[*] ")
            << "integrator.atol_spec = " << integrator_rp::atol_spec
            << std::endl;
jobInfoFile << (integrator_rp::atol_enuc == 1.e-6_rt ? "    " : "[*] ")
            << "integrator.atol_enuc = " << integrator_rp::atol_enuc
            << std::endl;
jobInfoFile << (integrator_rp::renormalize_abundances == false ? "    "
                                                               : "[*] ")
            << "integrator.renormalize_abundances = "
            << integrator_rp::renormalize_abundances << std::endl;
jobInfoFile << (integrator_rp::SMALL_X_SAFE == 1.0e-30_rt ? "    " : "[*] ")
            << "integrator.SMALL_X_SAFE = " << integrator_rp::SMALL_X_SAFE
            << std::endl;
jobInfoFile << (integrator_rp::MAX_TEMP == 1.0e11_rt ? "    " : "[*] ")
            << "integrator.MAX_TEMP = " << integrator_rp::MAX_TEMP << std::endl;
jobInfoFile << (integrator_rp::react_boost == -1.e0_rt ? "    " : "[*] ")
            << "integrator.react_boost = " << integrator_rp::react_boost
            << std::endl;
jobInfoFile << (integrator_rp::ode_max_steps == 150000 ? "    " : "[*] ")
            << "integrator.ode_max_steps = " << integrator_rp::ode_max_steps
            << std::endl;
jobInfoFile << (integrator_rp::ode_max_dt == 1.e30_rt ? "    " : "[*] ")
            << "integrator.ode_max_dt = " << integrator_rp::ode_max_dt
            << std::endl;
jobInfoFile << (integrator_rp::use_jacobian_caching == true ? "    " : "[*] ")
            << "integrator.use_jacobian_caching = "
            << integrator_rp::use_jacobian_caching << std::endl;
jobInfoFile << (integrator_rp::nonaka_i == 0 ? "    " : "[*] ")
            << "integrator.nonaka_i = " << integrator_rp::nonaka_i << std::endl;
jobInfoFile << (integrator_rp::nonaka_j == 0 ? "    " : "[*] ")
            << "integrator.nonaka_j = " << integrator_rp::nonaka_j << std::endl;
jobInfoFile << (integrator_rp::nonaka_k == 0 ? "    " : "[*] ")
            << "integrator.nonaka_k = " << integrator_rp::nonaka_k << std::endl;
jobInfoFile << (integrator_rp::nonaka_level == 0 ? "    " : "[*] ")
            << "integrator.nonaka_level = " << integrator_rp::nonaka_level
            << std::endl;
jobInfoFile << (integrator_rp::nonaka_file == "nonaka_plot.dat" ? "    "
                                                                : "[*] ")
            << "integrator.nonaka_file = " << integrator_rp::nonaka_file
            << std::endl;
jobInfoFile << (integrator_rp::use_burn_retry == false ? "    " : "[*] ")
            << "integrator.use_burn_retry = " << integrator_rp::use_burn_retry
            << std::endl;
jobInfoFile << (integrator_rp::retry_swap_jacobian == true ? "    " : "[*] ")
            << "integrator.retry_swap_jacobian = "
            << integrator_rp::retry_swap_jacobian << std::endl;
jobInfoFile << (integrator_rp::retry_rtol_spec == -1_rt ? "    " : "[*] ")
            << "integrator.retry_rtol_spec = " << integrator_rp::retry_rtol_spec
            << std::endl;
jobInfoFile << (integrator_rp::retry_rtol_enuc == -1_rt ? "    " : "[*] ")
            << "integrator.retry_rtol_enuc = " << integrator_rp::retry_rtol_enuc
            << std::endl;
jobInfoFile << (integrator_rp::retry_atol_spec == -1_rt ? "    " : "[*] ")
            << "integrator.retry_atol_spec = " << integrator_rp::retry_atol_spec
            << std::endl;
jobInfoFile << (integrator_rp::retry_atol_enuc == -1_rt ? "    " : "[*] ")
            << "integrator.retry_atol_enuc = " << integrator_rp::retry_atol_enuc
            << std::endl;
jobInfoFile << (integrator_rp::do_species_clip == true ? "    " : "[*] ")
            << "integrator.do_species_clip = " << integrator_rp::do_species_clip
            << std::endl;
jobInfoFile << (integrator_rp::use_number_densities == false ? "    " : "[*] ")
            << "integrator.use_number_densities = "
            << integrator_rp::use_number_densities << std::endl;
jobInfoFile << (integrator_rp::subtract_internal_energy == true ? "    "
                                                                : "[*] ")
            << "integrator.subtract_internal_energy = "
            << integrator_rp::subtract_internal_energy << std::endl;
jobInfoFile << (integrator_rp::scale_system == false ? "    " : "[*] ")
            << "integrator.scale_system = " << integrator_rp::scale_system
            << std::endl;
jobInfoFile << (integrator_rp::nse_deriv_dt_factor == 0.05_rt ? "    " : "[*] ")
            << "integrator.nse_deriv_dt_factor = "
            << integrator_rp::nse_deriv_dt_factor << std::endl;
jobInfoFile << (integrator_rp::nse_include_enu_weak == true ? "    " : "[*] ")
            << "integrator.nse_include_enu_weak = "
            << integrator_rp::nse_include_enu_weak << std::endl;
jobInfoFile << (integrator_rp::linalg_do_pivoting == true ? "    " : "[*] ")
            << "integrator.linalg_do_pivoting = "
            << integrator_rp::linalg_do_pivoting << std::endl;
