if(BUILD_TESTING AND AMReX_SPACEDIM EQUAL 3)
  add_executable(NSCBCIndexingTest NSCBCIndexingTest.cpp ${gamma_law_sources})
  target_include_directories(NSCBCIndexingTest PRIVATE ${PROJECT_SOURCE_DIR}/src)
  target_compile_features(NSCBCIndexingTest PRIVATE cxx_std_20)
  target_link_libraries(NSCBCIndexingTest PRIVATE AMReX::amrex)
  if(AMReX_GPU_BACKEND MATCHES "CUDA")
    setup_target_for_cuda_compilation(NSCBCIndexingTest)
  endif()
  add_test(NAME NSCBCIndexingTest COMMAND NSCBCIndexingTest)
endif()
