#!/bin/bash

#PBS -N quokka_GPU_8nodes
#PBS -P jh2
#PBS -q gpuvolta
#PBS -l ncpus=384
#PBS -l ngpus=32
#PBS -l mem=3056GB
#PBS -m aeb
#PBS -M ben.wibking@anu.edu.au
#PBS -l wd
#PBS -l walltime=2:00:00
#PBS -l storage=scratch/jh2+gdata/jh2
#PBS -l jobfs=3200GB

# --- initialize Quokka ---
MPI_OPTIONS="-np $PBS_NGPUS --map-by numa:SPAN --bind-to numa --mca pml ucx"
echo "Using MPI_OPTIONS = $MPI_OPTIONS"

mpirun $MPI_OPTIONS ./scripts/gpu_wrapper_shell_1024.sh > shell_8nodes.log






