# *****************************************************************
# Problem size and geometry
# *****************************************************************
geometry.prob_lo = [0.0, 0.0, 0.0]
geometry.prob_hi = [1.0, 1.0, 1.0]
quokka.bc = ["ext_dir", "periodic", "periodic"]

# *****************************************************************
# VERBOSITY
# *****************************************************************
amr.v = 1  # verbosity in Amr

# *****************************************************************
# Resolution and refinement
# *****************************************************************
amr.n_cell = [512, 16, 16]
amr.max_level = 0  # number of levels = max_level + 1

amr.max_grid_size_x = 512
amr.max_grid_size_y = 16
amr.max_grid_size_z = 16
amr.blocking_factor_x = 16
amr.blocking_factor_y = 16
amr.blocking_factor_z = 16

do_reflux = 0
do_subcycle = 0

plotfile_interval = 100
checkpoint_interval = -1
cfl = 0.4
stop_time = 0.15
max_timesteps = 2000

hydro.rk_integrator_order = 2
hydro.reconstruction_order = 5
hydro.use_dual_energy = 0

mhd.emf_averaging_scheme = "LondrilloDelZanna2004"
mhd.emf_compute_scheme = "Balsara2025"
