# *****************************************************************
# Problem size and geometry
# *****************************************************************
geometry.prob_lo = [0.0, 0.0, 0.0]
geometry.prob_hi = [1.0e24, 1.0e24,  1.0e24]         # 0.324077  0.324077 0.324077  Mpc
quokka.bc = ["periodic", "periodic", "periodic"]


# *****************************************************************
# Resolution and refinement
# *****************************************************************
amr.n_cell          = [32, 32, 32]
amr.max_level       = 0             # number of levels = max_level + 1
amr.blocking_factor = 8             # grid size must be divisible by this

max_timesteps  = 20000000
cfl            = 0.3


# *****************************************************************
# Cosmology
# *****************************************************************
cosmology.hubble_constant = 0.7
cosmology.omega_m         = 1.0    # Einstein-de Sitter  
cosmology.omega_b         = 1.0    # only ordinary matter
cosmology.omega_dm        = 0.0  
cosmology.omega_lambda    = 0.0
cosmology.a_init          = 1e-3   # CMB time
cosmology.a_final         = 10     # in the future


# *****************************************************************
# Problem specific parameters
# *****************************************************************
problem.rho0  = 1.0e-30      # initial density (comoving)
problem.P0    = 1.0e-25      # initial pressure (for small dt)
problem.vx0   = 5.77e4       # (5*10^5)/3
problem.vy0   = 5.77e4        
problem.vz0   = 5.77e4


# *****************************************************************
# Simulation control
# *****************************************************************
plotfile_interval = 500         # save a plotfile every plotfile_interval timesteps
amr.v = 1                       # AMReX verbosity level: 0=quiet, 1=verbose, 2=very verbose