# *****************************************************************
# Problem size and geometry
# *****************************************************************
geometry.prob_lo     =  0.0  0.0  0.0 
geometry.prob_hi     =  1.1e19 1.1e19 1.1e91
quokka.bc = reflecting reflecting reflecting

# *****************************************************************
# VERBOSITY
# *****************************************************************
amr.v              = 0       # verbosity in Amr

# *****************************************************************
# Resolution and refinement
# *****************************************************************
amr.n_cell          = 64 64 64
amr.max_level       = 0     # number of levels = max_level + 1
#max_timesteps = 10
do_reflux = 0
do_subcycle = 0
suppress_output = 0

stromgen.tend = 1.9e13
stromgen.primary_species_1 = 1.0e-10
stromgen.primary_species_2 = 139.9
stromgen.primary_species_3 = 1.0e-10
stromgen.Q = 4e46
stromgen.temperature = 37.11

photochemistry.enabled = 1
integrator.use_number_densities = 1
integrator.do_species_clip = 0
integrator.jacobian = 1
integrator.renormalize_abundances = 0
integrator.subtract_internal_energy = 0
integrator.X_reject_buffer = 1e100
integrator.ode_max_steps = 1500000

plotfile_interval = 10
plotfile_prefix = DType

network.allow_mixed_cell_cooling = 0
