# *****************************************************************
# Problem size and geometry
# *****************************************************************
geometry.prob_lo = [0.0, 0.0, 0.0]
geometry.prob_hi = [1.0, 1.0, 1.0]
quokka.bc = ["periodic", "periodic", "periodic"]

# *****************************************************************
# Verbosity
# *****************************************************************
amr.v = 0

# *****************************************************************
# Resolution and refinement
# *****************************************************************
amr.n_cell = [8, 8, 16]
amr.max_level = 0
amr.blocking_factor = 8
amr.max_grid_size = 16

do_reflux = 0
do_subcycle = 0
suppress_output = 1

plotfile_interval = -1
checkpoint_interval = -1

cfl = 0.3
stop_time = 5.0
max_timesteps = 20000

mhd.emf_compute_scheme = "Balsara2025"
mhd.emf_averaging_scheme = "Balsara2025"

dust.density_floor = 1.0e-14

[problem]
write_csv = 1
reference_steps = 20000
