geometry.prob_lo = [0.0, 0.0, 0.0]
geometry.prob_hi = [3.2e20, 3.2e20, 3.2e20]
quokka.bc = ["periodic", "periodic", "periodic"]

amr.n_cell = [32, 32, 32]
amr.max_level = 0
amr.blocking_factor = 16
amr.max_grid_size = 16
amr.n_error_buf = 3

initial_dt = "1.0 * Myr"
max_timesteps = 0
do_reflux = 0
do_subcycle = 0

particles.disable_particle_drift = true
particles.SN_scheme = "SN_thermal_only"
particles.imf_particle_mass_msun = 0.1
particles.imf_random_seed = 1234
particles.verbose = 0

plotfile_interval = -1
checkpoint_interval = -1
statistics_interval = -1
tiny_profiler.enabled = 0
