# *****************************************************************
# Problem size and geometry
# *****************************************************************
geometry.prob_lo = [0.0, 0.0, 0.0]
geometry.prob_hi = [1.0, 1.0, 1.0]
quokka.bc = ["periodic", "periodic", "periodic"]

# *****************************************************************
# Verbosity
# *****************************************************************
amr.v = 1

# *****************************************************************
# Resolution and refinement
# *****************************************************************
amr.n_cell = [16, 16, 16]
amr.max_level = 0
amr.max_grid_size = 16
amr.blocking_factor_x = 16
amr.blocking_factor_y = 16
amr.blocking_factor_z = 16

# *****************************************************************
# Solver
# *****************************************************************
do_reflux = 0
do_subcycle = 0

cfl = 0.3
stop_time = 2.0
max_timesteps = 10000

hydro.use_dual_energy = 0

# *****************************************************************
# Problem setup
# *****************************************************************
setup.num_modes_x = 1
setup.num_modes_y = 1
setup.num_modes_z = 0
setup.angle_between_k_b0 = 0
