# *****************************************************************
# Problem size and geometry
# *****************************************************************
# Box is [-10 kpc, 10 kpc] x [-10 kpc, 10 kpc] x [-10 kpc, 10 kpc]
geometry.prob_lo     = -3.0856775814913674e22 -3.0856775814913674e22 -3.0856775814913674e22
geometry.prob_hi     =  3.0856775814913674e22  3.0856775814913674e22  3.0856775814913674e22
geometry.is_periodic = [0, 0, 0]
amr.v = 2
# *****************************************************************
# Resolution and refinement
# *****************************************************************
amr.n_cell = 256 256 256
amr.blocking_factor = 32
amr.max_grid_size   = 64
amr.max_level       = 3
amr.n_error_buf     = 2
amr.grid_eff        = 0.75
regrid_interval     = -1
do_reflux           = 1
do_subcycle         = 0
plotfile_prefix = "tests/plt/mhdplt_Q1"
checkpoint_prefix = "tests/chk/mhdchk_Q1"
statistics_prefix = "tests/mhdstats_Q1.txt"
statistics_interval = 1
density_floor = 1.0e-32
# *****************************************************************
# Time integration
# *****************************************************************
cfl                 = 0.3
max_timesteps       = 1
stop_time           = 2.9652e15   # ~94 Myr = 1 t_rot at R=3 kpc, vc=200 km/s
# *****************************************************************
# Output
# *****************************************************************
checkpoint_interval = 100
plotfile_interval   = 10
derived_vars        = gpot pressure radius_sph radial_velocity circular_velocity mach plasma_beta divB Bphi
# *****************************************************************
# Problem parameters (Table 1, Q1_M29)
# *****************************************************************
mhd_galaxy.Q_mean    = 0.96
mhd_galaxy.Mc        = 28.6
mhd_galaxy.sn_jeans_J              = 4.0
mhd_galaxy.sn_remnant_fraction     = 0.5
mhd_galaxy.sn_momentum             = 3.0e3

mhd.project_initial_b_field = true
mhd.update_initial_b_energy = true
