# *****************************************************************
# Problem size and geometry
# *****************************************************************
# Box is [-10 kpc, 10 kpc] x [-10 kpc, 10 kpc] x [-10 kpc, 10 kpc]
geometry.prob_lo     = -3.0856775814913674e22 -3.0856775814913674e22 -3.0856775814913674e22
geometry.prob_hi     =  3.0856775814913674e22  3.0856775814913674e22  3.0856775814913674e22
geometry.is_periodic = [0, 0, 0]
amr.v = 2
# *****************************************************************
# Resolution and refinement
# *****************************************************************
amr.n_cell = 256 256 256
amr.blocking_factor_x = 128
amr.blocking_factor_y = 128
amr.blocking_factor_z = 16
amr.max_grid_size   = 128
amr.max_level       = 3
amr.n_error_buf     = 2
amr.grid_eff        = 0.75
regrid_interval     = -1
do_reflux           = 1
do_subcycle         = 0
plotfile_prefix = "tests/plt/mhddisk_Q1turb_plt"
checkpoint_prefix = "tests/chk/mhddisk_Q1turb_chk"
statistics_file = "tests/mhddiskstats_Q1turb.txt"
statistics_interval = 1
density_floor = 1.0e-32
restartfile = "tests/chk/mhddisk_Q1turb_chk0029771"
# *****************************************************************
# Time integration
# *****************************************************************
cfl                 = 0.3
max_timesteps       = 1e8
stop_time           = 1.18608e16   # ~94 Myr = 1 t_rot at R=3 kpc, vc=200 km/s, 4 rotations
# *****************************************************************
# Output
# *****************************************************************
checkpointtime_interval = 1.4826e14
plottime_interval   = 1.4826e14
derived_vars        = gpot pressure radius_sph radial_velocity circular_velocity mach plasma_beta divB Bphi
# *****************************************************************
# Problem parameters (Table 1, Q1_M29)
# *****************************************************************
mhd_galaxy.Q_mean    = 0.96
mhd_galaxy.Mc        = 28.6
mhd_galaxy.sn_jeans_J              = 4.0
mhd_galaxy.sn_remnant_fraction     = 0.5
mhd_galaxy.sn_momentum             = 3.0e3

mhd.project_initial_b_field = true
mhd.update_initial_b_energy = true

mhd_galaxy.turb_vx_file = tests/input/vx.bin
mhd_galaxy.turb_vy_file = tests/input/vy.bin
mhd_galaxy.turb_vz_file = tests/input/vz.bin
mhd_galaxy.aphi_meta_file = tests/input/Aphi_2d_meta.txt
mhd_galaxy.aphi_data_file = tests/input/Aphi_2d_Aphi.bin


quokka.diagnostics = slice_z slice_x proj_z        # Space-separated name(s) of diagnostics (arbitrary)

quokka.proj_z.type = ProjectionPlot
quokka.proj_z.file = tests/projz/projz2_plt
quokka.proj_z.time_int = 2.9652e13
quokka.proj_z.normal = 2
quokka.proj_z.field_names = Bphi gasDensity x-BField y-BField z-BField x-GasMomentum y-GasMomentum z-GasMomentum 

quokka.slice_z.type = DiagFramePlane
quokka.slice_z.file = tests/slicez/slicez2_plt
quokka.slice_z.normal = 2
quokka.slice_z.center = 0.0
quokka.slice_z.time_int = 2.9652e12
quokka.slice_z.field_names = Bphi x-BField y-BField z-BField x-GasMomentum y-GasMomentum z-GasMomentum plasma_beta

quokka.slice_x.type = DiagFramePlane
quokka.slice_x.file = tests/slicex/slicex2_plt
quokka.slice_x.normal = 0
quokka.slice_x.center = 0.0
quokka.slice_x.time_int = 2.9652e12
quokka.slice_x.field_names = Bphi x-BField y-BField z-BField x-GasMomentum y-GasMomentum z-GasMomentum plasma_beta
