# *****************************************************************
# PROBLEM SIZE AND GEOMETRY
# *****************************************************************
geometry.prob_lo = [-1.0, -0.578125, -1.0]
geometry.prob_hi = [1.0, 0.578125, 1.0]
quokka.bc = ["periodic", "periodic", "periodic"]

# *****************************************************************
# VERBOSITY
# *****************************************************************
amr.v = 0

# *****************************************************************
# RESOLUTION AND REFINEMENT
# *****************************************************************
amr.n_cell = [128, 64, 8]
amr.max_level = 0  # number of levels = max_level + 1
amr.max_grid_size = 128
amr.blocking_factor_x = 32
amr.blocking_factor_y = 32
amr.blocking_factor_z = 8

# *****************************************************************
# SOLVER
# *****************************************************************
do_reflux = 0
do_subcycle = 0

cfl = 0.2
stop_time = 3.0
max_timesteps = 3e4

hydro.use_dual_energy = 0
