# *****************************************************************
# Boundary conditions
# *****************************************************************
quokka.bc = ["periodic", "periodic", "periodic"]

# *****************************************************************
# Verbosity
# *****************************************************************
amr.v = 0

# *****************************************************************
# Resolution and refinement
# *****************************************************************
amr.max_level = 0
amr.blocking_factor = 8
amr.max_grid_size = 128

# *****************************************************************
# Solver
# *****************************************************************
cfl = 0.3

hydro.reconstruction_order = 5
hydro.use_dual_energy = 0

mhd.emf_reconstruction_order = 5

# *****************************************************************
# Problem setup
# *****************************************************************
setup.num_modes_x = 1
setup.num_modes_y = 0
setup.num_modes_z = 0
setup.angle_between_k_b0 = 90
