# *****************************************************************
# PROBLEM SIZE AND GEOMETRY
# *****************************************************************
geometry.prob_lo = [0.0, 0.0, 0.0]
geometry.prob_hi = [1.0, 0.125, 1.0]
geometry.is_periodic = [0, 1, 1]  # must be set explicitly since BCs are code-defined (no quokka.bc)

# *****************************************************************
# VERBOSITY
# *****************************************************************
amr.v = 0

# *****************************************************************
# RESOLUTION AND REFINEMENT
# *****************************************************************
amr.n_cell = [128, 16, 16]
amr.max_level = 0
amr.blocking_factor = 16
amr.max_grid_size = 128

# *****************************************************************
# SOLVER
# *****************************************************************
do_reflux = 0
do_subcycle = 0

hydro.use_dual_energy = 0
