# *****************************************************************
# Problem size and geometry
# *****************************************************************
geometry.prob_lo = [0.0, 0.0, 0.0]
geometry.prob_hi = [64.0, 1.0, 1.0]
quokka.bc = ["periodic", "periodic", "periodic"]

# *****************************************************************
# Resolution and refinement
# *****************************************************************
amr.v = 0
amr.n_cell = [64, 8, 8]
amr.max_level = 1  # level 1 covers all of level 0
amr.blocking_factor = 8
amr.max_grid_size = 64

do_reflux = 1
do_subcycle = 0
suppress_output = 1
