geometry.prob_lo = [0.0, 0.0, 0.0]
geometry.prob_hi = [1.0, 1.0, 1.0]
quokka.bc = ["periodic", "periodic", "periodic"]
amr.n_cell = [16, 16, 16]
amr.max_level = 1
amr.blocking_factor = 8
do_subcycle = 0
do_reflux = 0
plotfile_interval = -1
checkpoint_interval = -1
max_timesteps = 1
fab.do_initval = 1
fab.initval = -9876.0
