# *****************************************************************
# Problem size and geometry
# *****************************************************************
# -80 pc to 80 pc, with 32 cells, dx = 5 pc
geometry.prob_lo = [-2.468542065e+20, -2.468542065e+20, -2.468542065e+20]
geometry.prob_hi = [2.468542065e+20, 2.468542065e+20, 2.468542065e+20]
quokka.bc = ["periodic", "periodic", "periodic"]

# *****************************************************************
# VERBOSITY
# *****************************************************************
amr.v = 0  # verbosity in Amr

# *****************************************************************
# Resolution and refinement
# *****************************************************************
amr.n_cell = [32, 32, 32]
amr.max_level = 0  # number of levels = max_level + 1
amr.blocking_factor = 32  # grid size must be divisible by this
amr.max_grid_size = 32  # at least 128 for GPUs
amr.n_error_buf = 3  # minimum 3 cell buffer around tagged cells
amr.grid_eff = 0.7  # default

do_reflux = 1
do_subcycle = 0
do_tracers = 0  # turn on tracer particles

hydro.artificial_viscosity_coefficient = 0.1

cooling.enabled = 1
cooling.cooling_table_type = "resampled"
cooling.hdf5_data_file = "../extern/cooling/CloudyData_UVB=HM2012_resampled.h5"
problem.SN_particles_file = "../inputs/SN.txt"
problem.refine_half_domain = false

problem.n_amb = 10.0
particles.SN_scheme = "SN_thermal_or_thermal_momentum"
particles.verbose = 1

max_timesteps = 100000
plotfile_interval = -1
checkpoint_interval = -1
initial_dt = 3.0e7
stop_time = 3.0e10

#temperature_floor = 10
density_floor = 1e-28
signal_speed_abort = 2e9
problem.boost_vel_x = 1.0e8

suppress_output = 0
tiny_profiler.enabled = 1

quokka.diagnostics = "part"
quokka.part.type = "ParticleTxt"  # Diagnostic type
quokka.part.file = "part_plt"  # Output file prefix (must end in "plt")
quokka.part.int = 10000
#quokka.part.time_int = 4e13
quokka.part.particles = "Test_particles"
