# *****************************************************************
# Problem size and geometry
# *****************************************************************
# 1x1x4 kpc box
geometry.prob_lo = [0.0, 0.0, -6.036e+21]
geometry.prob_hi = [3.018e21, 3.018e21, 6.036e+21]
quokka.bc = ["periodic", "periodic", "ext_dir"]

# *****************************************************************
# VERBOSITY
# *****************************************************************
amr.v = 1  # verbosity in Amr

# *****************************************************************
# Resolution and refinement
# *****************************************************************
amr.n_cell = [32, 32, 128]
amr.max_level = 0  # number of levels = max_level + 1
amr.max_grid_size = 128  # at least 128 for GPUs
amr.blocking_factor = 32  # grid size must be divisible by this
amr.n_error_buf = 0  # need 0 to enforce exact refinement boundaries
amr.grid_eff = 0.0

cfl = 0.3
do_reflux = 1
do_subcycle = 0

plottime_interval = 3.155760000e+14  # 1e7 yr
checkpointtime_interval = 6.311520000e+14  # 2e7 yr
stop_time = 6.31152e15  # 200 Myr  
max_timesteps = 100
#restartfile = last_chk
suppress_output = 0
regrid_interval = -1
# be careful about Poisson supercycling
poisson_supercycle_interval = 2

particles.verbose = 0
particles.disable_SN_feedback = false
particles.split_particles_on_restart_refine = false

# metal scalar
particles.scalar_yield_per_SN = 1.99e33  # 1 Msun, given a density of 6e-29 when spreaded in a sphere of radius 64 pc
problem.initial_scalar_density = 1.67e-35  # 1e-11 mH/cm^3


density_floor = 1.67e-28  #in g cm^-3
temperature_floor = 10.0  #K

particles.eps_ff = 0.01
problem.stars_file = ""
problem.IC_file = "../extern/problems/TallBoxSf/disk_solution_datatable_Sigma13-Z1.csv"
problem.rho01 = 4.320441e-24
problem.sigma1 = 7.0e5

cooling.enabled = 1
cooling.cooling_table_type = "resampled"
cooling.hdf5_data_file = "../extern/cooling/CloudyData_UVB=HM2012_shielded_resampled_noPE.h5"
use_sfh_based_pe_heating = true
sfh_to_pe_heating_table = "../extern/cooling/photoelectric_heating_from_sfh.csv"
sfh_time_interval = 3.155760000e+12  # 1e5 yr
sf_area_kpc2 = 1.0  # kpc^2

perturb.filename = "zdrv.hdf5"
perturb.amplitude = 7e5  # 7 km/s

statistics_interval = 512

derived_vars = ["temperature", "c_s", "gpot", "scalar0_z_outflow_rate", "hot_gas_z_outflow_rate", "warm_gas_z_outflow_rate", "hot_scalar0_z_outflow_rate", "warm_scalar0_z_outflow_rate"]

quokka.diagnostics = ["slice_x", "slice_z", "proj"]

quokka.slice_x.type = "DiagFramePlane"
quokka.slice_x.file = "slicex_plt"
quokka.slice_x.normal = 0  # Plane normal (0 == x, 1 == y, 2 == z)
quokka.slice_x.center = 1.509001e21
quokka.slice_x.time_int = 3.155760000e+13  # 1e6 yr
quokka.slice_x.field_names = ["gasDensity", "gasEnergy", "x-GasMomentum", "y-GasMomentum", "z-GasMomentum", "temperature", "c_s", "gpot", "scalar0_z_outflow_rate", "hot_gas_z_outflow_rate", "warm_gas_z_outflow_rate", "hot_scalar0_z_outflow_rate", "warm_scalar0_z_outflow_rate"]
quokka.slice_x.particles = "StochasticStellarPop_particles"

quokka.slice_z.type = "DiagFramePlane"
quokka.slice_z.file = "slicez_plt"
quokka.slice_z.normal = 2  # Plane normal (0 == x, 1 == y, 2 == z)
quokka.slice_z.center = 1.0e12  # Domain center in the normal direction
quokka.slice_z.time_int = 3.155760000e+13  # 1e6 yr
quokka.slice_z.field_names = ["gasDensity", "gasEnergy", "x-GasMomentum", "y-GasMomentum", "z-GasMomentum", "temperature", "c_s", "gpot", "scalar0_z_outflow_rate", "hot_gas_z_outflow_rate", "warm_gas_z_outflow_rate", "hot_scalar0_z_outflow_rate", "warm_scalar0_z_outflow_rate"]
quokka.slice_z.particles = "StochasticStellarPop_particles"

quokka.proj.type = "ProjectionPlot"  # Projection plot diagnostic
quokka.proj.file = "proj_plt"  # Output file prefix (must end in "plt")
quokka.proj.time_int = 3.155760000e+13  # 1e6 yr
quokka.proj.normal = 0  # Plane normal (0 == x, 1 == y, 2 == z)
quokka.proj.field_names = ["gasDensity", "z-GasMomentum", "scalar0_z_outflow_rate", "hot_gas_z_outflow_rate", "warm_gas_z_outflow_rate", "hot_scalar0_z_outflow_rate", "warm_scalar0_z_outflow_rate"]
quokka.proj.particles = "StochasticStellarPop_particles"

