# *****************************************************************
# Problem size and geometry
# *****************************************************************
geometry.prob_lo = [-1.5428e18, -1.5428e18, -1.5428e18]
geometry.prob_hi = [1.5428e18, 1.5428e18, 1.5428e18]
geometry.is_periodic = [0, 0, 0]
quokka.bc = ["foextrap", "foextrap", "foextrap"]

# *****************************************************************
# VERBOSITY
# *****************************************************************
amr.v = 1      # verbosity in Amr

# *****************************************************************
# Resolution and refinement
# (nx/max_level are actually set programmatically in problem_main's resolution sweep;
# these are just placeholder defaults)
# *****************************************************************
amr.n_cell = [128, 128, 128]
amr.max_level = 0
amr.blocking_factor = 16  # grid size must be divisible by this

do_reflux = 1
do_subcycle = 0

cfl = 0.3

conduction.enabled = 1
conduction.flux_limiter_phi = 1
conduction.saturation_factor = 1.2e20
conduction.conduction_cfl = 0.1
suppress_output = 0

conduction.conduction_type = "spitzer"
conduction.conductivity_prefactor = 5.40e-10
