add_executable(DiagnosticStateTest testDiagnosticState.cpp ../DiagBase.cpp ../DiagFilter.cpp)
target_link_libraries(DiagnosticStateTest PRIVATE AMReX::amrex yaml-cpp::yaml-cpp)
target_include_directories(DiagnosticStateTest PRIVATE .. ../..)
target_compile_features(DiagnosticStateTest PRIVATE cxx_std_20)
if(AMReX_SPACEDIM EQUAL 3)
  target_sources(DiagnosticStateTest PRIVATE ../DiagProjectionPlot.cpp)
endif()
if(AMReX_GPU_BACKEND MATCHES "CUDA")
  setup_target_for_cuda_compilation(DiagnosticStateTest)
endif()
add_test(NAME DiagnosticStateTest COMMAND DiagnosticStateTest)
