# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pr:
  autoCancel: true
  branches:
    include:
    - development
  paths:
    include:
    - src/*
    - inputs/*
    - CMakeLists.txt
    - .ci/*
    - extern/amrex
    - extern/Microphysics
    - extern/fmt
    - extern/yaml-cpp
    - extern/openPMD-api
    exclude:
    - docs/*
    - paper/*
    - scripts/*
    - '*.md'
    - '*.rst'
    - '*.txt'

variables:
  cacheKeySuffix: $[replace(variables['Build.SourceBranch'], '/', '_')]

jobs:
  - job: CUDA_Build_Test
    pool: avatar
    timeoutInMinutes: 120
    steps:
    - task: Cache@2
      displayName: Restore ccache
      inputs:
        key: 'ccache | CUDA | $(Agent.OS) | $(cacheKeySuffix)'
        restoreKeys: |
          ccache | CUDA | $(Agent.OS)
        path: $(Pipeline.Workspace)/ccache

    - script: |
        if ! command -v ccache >/dev/null 2>&1; then
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ccache
        fi
      displayName: Ensure ccache

    - script: |
        mkdir -p $(Pipeline.Workspace)/ccache
        ccache --zero-stats || true
      displayName: Prepare ccache
      env:
        CCACHE_DIR: $(Pipeline.Workspace)/ccache

    - task: CMake@1
      displayName: 'Configure CMake'
      env:
        CCACHE_DIR: $(Pipeline.Workspace)/ccache
        CCACHE_BASEDIR: $(Build.SourcesDirectory)
        CCACHE_NOHASHDIR: 1
      inputs:
        cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release -DAMReX_SPACEDIM=3 -DAMReX_GPU_BACKEND=CUDA -DQUOKKA_PYTHON=OFF -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache'
    
    - task: CMake@1
      displayName: 'Build Quokka'
      env:
        CCACHE_DIR: $(Pipeline.Workspace)/ccache
        CCACHE_BASEDIR: $(Build.SourcesDirectory)
        CCACHE_NOHASHDIR: 1
      inputs:
        cmakeArgs: '--build . --parallel 16'
    
    - task: CMake@1
      displayName: 'Run CTest'
      inputs:
        cmakeArgs: '-E chdir . ctest -E "MatterEnergyExchange*" -T Test --output-on-failure'
    
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: cTest
        testResultsFiles: build/Testing/*/Test.xml
        testRunTitle: $(Agent.JobName)
      condition: succeededOrFailed()
      displayName: Publish test results

    - script: |
        ccache --show-stats || true
      displayName: Report ccache statistics
      condition: succeededOrFailed()
      env:
        CCACHE_DIR: $(Pipeline.Workspace)/ccache
