if (AMReX_SPACEDIM EQUAL 3)
    add_executable(TallBoxSf0 testTallBoxSf0.cpp ../../turbulence/TurbDataReader.cpp ${QuokkaObjSources})
    if(AMReX_GPU_BACKEND MATCHES "CUDA")
        setup_target_for_cuda_compilation(TallBoxSf0)
    endif()
    add_test(NAME TallBoxSf0 COMMAND TallBoxSf0 ../inputs/TallBoxSf0.in ${QuokkaTestParams} WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/tests)
endif()
