if (AMReX_SPACEDIM EQUAL 3)
    add_executable(ProdGalaxyTallBoxNoGgas ProdGalaxyTallBoxNoGgas.cpp ../../turbulence/TurbDataReader.cpp ${QuokkaObjSources})
    if(AMReX_GPU_BACKEND MATCHES "CUDA")
        setup_target_for_cuda_compilation(ProdGalaxyTallBoxNoGgas)
    endif()
    add_test(NAME ProdGalaxyTallBoxNoGgas COMMAND ProdGalaxyTallBoxNoGgas ../inputs/ProdGalaxyTallBoxNoGgas.in ${QuokkaTestParams} WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/tests)
endif()
