if(BUILD_TESTING AND AMReX_SPACEDIM EQUAL 3)
  add_executable(NSCBCSonicTest NSCBCSonicTest.cpp ${gamma_law_sources})
  target_include_directories(NSCBCSonicTest PRIVATE ${PROJECT_SOURCE_DIR}/src)
  target_compile_features(NSCBCSonicTest PRIVATE cxx_std_20)
  target_link_libraries(NSCBCSonicTest PRIVATE AMReX::amrex)
  if(AMReX_GPU_BACKEND MATCHES "CUDA")
    setup_target_for_cuda_compilation(NSCBCSonicTest)
  endif()
  add_test(NAME NSCBCSonicTest COMMAND NSCBCSonicTest)
endif()
