#!/bin/bash

#PBS -N quokka_CPU_1node
#PBS -P jh2
#PBS -q normal
#PBS -l ncpus=48
#PBS -l mem=190GB
#PBS -m aeb
#PBS -M ben.wibking@anu.edu.au
#PBS -l wd
#PBS -l walltime=1:00:00
#PBS -l storage=scratch/jh2+gdata/jh2
#PBS -l jobfs=400GB

# --- initialize Quokka ---
MPI_OPTIONS="-np $PBS_NCPUS --mca pml ucx"
echo "Using MPI_OPTIONS = $MPI_OPTIONS"

mpirun $MPI_OPTIONS ./scripts/gpu_wrapper_sedov_512.sh > sedov.log






