#!/bin/bash

#PBS -N quokka_GPU_2node
#PBS -P jh2
#PBS -q gpuvolta
#PBS -l ncpus=96
#PBS -l ngpus=8
#PBS -l mem=764GB
#PBS -m aeb
#PBS -M ben.wibking@anu.edu.au
#PBS -l wd
#PBS -l walltime=0:30:00
#PBS -l storage=scratch/jh2+gdata/jh2
#PBS -l jobfs=800GB

# --- initialize Quokka ---
MPI_OPTIONS="-np $PBS_NGPUS --map-by numa:SPAN --bind-to numa --mca pml ucx -x UCX_TLS=rc,sm,cuda_copy,cuda_ipc"
echo "Using MPI_OPTIONS = $MPI_OPTIONS"

mpirun $MPI_OPTIONS ./gpu_wrapper_sedov.sh > sedov.log






