#!/bin/bash

#PBS -N quokka_GPU_1node
#PBS -P jh2
#PBS -q gpuvolta
#PBS -l ncpus=48
#PBS -l ngpus=4
#PBS -l mem=382GB
#PBS -m aeb
#PBS -M ben.wibking@anu.edu.au
#PBS -l wd
#PBS -l walltime=0:30:00
#PBS -l storage=scratch/jh2+gdata/jh2
#PBS -l jobfs=400GB

# --- initialize Quokka ---
MPI_OPTIONS="-np $PBS_NGPUS --map-by numa:SPAN --bind-to numa --mca pml ucx"
echo "Using MPI_OPTIONS = $MPI_OPTIONS"

mpirun $MPI_OPTIONS ./scripts/gpu_wrapper_sedov_512.sh > sedov_1node.log






