site_name: Quokka
docs_dir: markdown
copyright: © Copyright 2020-2025, Ben Wibking and Quokka Developers.
theme:
  name: material
  favicon: media/quokka-favicon.svg
  font:
    text: Source Sans Pro
  features:
    - navigation.expand
    - content.code.copy
    - content.code.select
nav:
  - Home: index.md
  - About: about.md
  - Equations: equations.md
  - Citation: citation.md
  - Glossary: glossary.md
  - Physics Modules:
    - Magnetohydrodynamics: mhd_module.md
    - Star Formation and Feedback: particles.md
    - Dust Module: dust_module.md
  - Simulation gallery:
    - Hydro: gallery.md
  - User guide:
    - Installation: installation.md
    - Running on HPC clusters: running_on_hpc_clusters.md
    - Grid refinement (AMR): amr_grid_refinement.md
    - Test problems:
      - Overview: tests/index.md
      - Table of all test problems: tests/table_of_all_problems.md
      - Radiative shock test: tests/radshock.md
      - Shu-Osher shock test: tests/shu_osher.md
      - Slow-moving shock test: tests/sms.md
      - Matter-radiation temperature equilibrium test: tests/energy_exchange.md
      - Uniform advecting radiation in diffusive limit: tests/radhydro_uniform_adv.md
      - Advecting radiation pulse test: tests/radhydro_pulse.md
    - Runtime parameters: parameters.md
    - In-situ analysis: insitu_analysis.md
    - Postprocessing: postprocessing.md
    - Debugging simulation instability: instability.md
    - Runtime calculator: html/runtime-calculator/index.html
  - Developer Guide:
    - Developer onboarding: developer_onboarding.md
    - Developing a new problem generator: developing_problem_generators.md
    - Contributing Guide: contributing.md
    - Flowchart: flowchart.md
    - Hydro Integrator: hydro_integrator.md
    - Radiation Integrator: radiation_integrator.md
    - State Variable Component Indices: components.md
    - Debugging: debugging.md
    - Assertions and error checking: error_checking.md
    - Performance tips: performance.md
    - How to use clang-tidy: howto_clang_tidy.md
  - Maintainer Guide:
    - Maintainer Guidelines: maintainer_guidelines.md
    - Architecture Decision Records: adrs.md
    - PR Revert Policy: pr_revert_policy.md

plugins:
  - search
  - awesome-pages
  - include-markdown
  - bibtex:
      bib_file: markdown/references.bib
      bib_by_default: true
      csl_file: apa-6th-edition.csl
      encoding: utf-8
  - mermaid2:
      version: 10.6.1

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - extra.css
