name: Check Changes

on:
  workflow_call:
    outputs:
      has_docs_changes:
        value: ${{ jobs.check.outputs.has_docs_changes }}
      has_non_docs_changes:
        value: ${{ jobs.check.outputs.has_non_docs_changes }}
      has_scripts_changes:
        value: ${{ jobs.check.outputs.has_scripts_changes }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has_docs_changes: ${{ steps.set-output.outputs.has_docs_changes }}
      has_non_docs_changes: ${{ steps.set-output.outputs.has_non_docs_changes }}
      has_scripts_changes: ${{ steps.set-output.outputs.has_scripts_changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            docs:
              - 'docs/**'
            scripts:
              - 'scripts/**'
            others:
              - '**'
              - '!.ci/**'
              - '!.github/**'
              - '!cmake/**'
              - '!docs/**'
              - '!paper/**'
              - '!scripts/**'
              - '!*.md'
              - '!*.rst'
              - '!.devcontainer/**'

      - id: set-output
        run: |
          echo "has_docs_changes=${{ steps.changes.outputs.docs }}" >> $GITHUB_OUTPUT
          echo "has_non_docs_changes=${{ steps.changes.outputs.others }}" >> $GITHUB_OUTPUT
          echo "has_scripts_changes=${{ steps.changes.outputs.scripts }}" >> $GITHUB_OUTPUT 