name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
# Fiewer paths are ignored because some folders (e.g. scripts) are not relavent to code build but should be linted
on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-clang-tidy
  cancel-in-progress: true

jobs:
  check_changes:
    uses: ./.github/workflows/check_changes.yml
    with:
      workflow_file: '.github/workflows/clang-tidy.yml'

  build:
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.has_non_docs_changes == 'true' || needs.check_changes.outputs.has_scripts_changes == 'true'

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy libopenmpi-dev libhdf5-mpi-dev python3-dev python3-numpy python3-matplotlib ccache

    - name: Set up cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ccache
        key: ccache-${{ github.workflow }}-${{ github.job }}-git-${{ github.sha }}
        restore-keys: |
             ccache-${{ github.workflow }}-${{ github.job }}-git-

    - name: Build Quokka & run clang-tidy
      run: |
        export CCACHE_COMPRESS=1
        export CCACHE_COMPRESSLEVEL=10
        export CCACHE_MAXSIZE=300M
        export CCACHE_EXTRAFILES=${{ github.workspace }}/src/.clang-tidy
        export CCACHE_LOGFILE=${{ github.workspace }}/ccache.log.txt
        ccache -z

        # Configure
        cmake -S . -B build \
          -DCMAKE_VERBOSE_MAKEFILE=ON \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DQUOKKA_PYTHON=ON \
          -DQUOKKA_OPENPMD=ON \
          -DopenPMD_USE_ADIOS2=OFF \
          -DAMReX_SPACEDIM=3 \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

        # Build to populate cache
        cmake --build build -j 4

        # Generate makefile for clang-tidy
        python3 ${{github.workspace}}/.github/workflows/scripts/makeMakefileForClangTidy.py --input ${{github.workspace}}/ccache.log.txt --identifier src

        # Run clang-tidy
        make -j4 --keep-going -f clang-tidy-ccache-misses.mak \
            CLANG_TIDY=clang-tidy \
            CLANG_TIDY_ARGS="--config-file=${{github.workspace}}/src/.clang-tidy"

        ccache -s
