name: ✍️ codespell

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development

permissions:
  contents: read

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          # this path is specific to Ubuntu
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r .github/workflows/dependencies/requirements.txt

      - name: Run codespell
        run: |
          codespell -I .github/workflows/codespell_ignore.txt, --ignore-words=.github/workflows/codespell_ignore.txt src
